version: "3.8"

services:
    db:
        image: mysql:latest
        environment:
            MYSQL_ROOT_PASSWORD: "password"
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        ports:
            - ${MYSQL_PORT}:3306
        networks:
            - symfony_app
    php:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        volumes:
            - ./:/var/www/symfony
        networks:
            - symfony_app
        expose:
            - 9000
        depends_on:
            - db
        restart: unless-stopped
    nginx:
        build:
            context: .
            dockerfile: docker/nginx/Dockerfile
        volumes:
            - ./:/var/www/symfony
        ports:
            - ${NGINX_PORT}:80
        networks:
            - symfony_app
        depends_on:
            - php
        restart: unless-stopped

networks:
    symfony_app:
